/**
 * Labeled synthetic corpus for Main RP completion-integrity JEV shadow benchmark.
 * Offline fixtures only — no real user chats, no Main RP provider generation.
 *
 * Expected verdicts are declared explicitly (never inferred from id).
 * Deterministic candidate discovery reuses existing responseLength / recovery owners.
 */
export type CompletionIntegrityVerdict = "ABRUPT_CUT" | "COMPLETE" | "UNCERTAIN";

export type CompletionIntegrityFixture = {
  id: string;
  finishReason: string | null;
  /** Delivered final visible prose under review (post local recovery if any). */
  finalProse: string;
  localRecoveryApplied: boolean;
  localRecoveryActions: string[];
  /** Human-declared whether deterministic candidate SHOULD fire. */
  expectDeterministicCandidate: boolean;
  expectedVerdict: CompletionIntegrityVerdict;
  rationale: string;
};

export const COMPLETION_INTEGRITY_CORPUS: readonly CompletionIntegrityFixture[] = [
  // —— Clear abrupt cuts ——
  {
    id: "CI_AC_01_predicate_stem",
    finishReason: "MAX_TOKENS",
    finalProse: "서린은 민의 손목을 잡은 채 조금 더 끌",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Predicate stem cut mid-verb after token limit.",
  },
  {
    id: "CI_AC_02_particle_tail",
    finishReason: "LENGTH",
    finalProse: "복도 끝에서 그가 돌아보며 말했다. 그래도",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Stops after connective particle with no completed clause.",
  },
  {
    id: "CI_AC_03_comma_cut",
    finishReason: "MAX_TOKENS",
    finalProse: "창밖의 빗소리가 커졌다. 서린은 숨을 고르며,",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Ends on comma mid-sentence.",
  },
  {
    id: "CI_AC_04_unclosed_quote",
    finishReason: "STOP",
    finalProse: "서린이 낮게 말했다. 「지금은 안 돼",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Unclosed dialogue quote — utterance unfinished.",
  },
  {
    id: "CI_AC_05_mid_action",
    finishReason: null,
    finalProse: "그는 문을 반쯤 열고 손잡이를",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Action interrupted mid-object; missing finishReason + incomplete.",
  },
  {
    id: "CI_AC_06_mid_hangul_word",
    finishReason: "MAX_TOKENS",
    finalProse: "민의 표정이 굳어지며 서린은 그 순간을 기억하",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Mid-word Hangul stem cut.",
  },
  {
    id: "CI_AC_07_mid_latin",
    finishReason: "LENGTH",
    finalProse: "그는 주머니에서 USB stick을 꺼내 d",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Mid-Latin letter cut.",
  },
  {
    id: "CI_AC_08_dash_cut",
    finishReason: "MAX_TOKENS",
    finalProse: "서린은 대답 대신 한숨을 내쉬었다— 그리고",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Ends after dash mid-continuation.",
  },
  {
    id: "CI_AC_09_colon_list",
    finishReason: "MAX_OUTPUT_TOKENS",
    finalProse: "책상 위에는 세 가지가 있었다: 열쇠,",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "List interrupted after first item and comma.",
  },

  // —— Clear complete (incl. scanner-positive complete) ——
  {
    id: "CI_OK_01_normal_sentence",
    finishReason: "STOP",
    finalProse: "서린은 창문을 닫고 천천히 소파에 앉았다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: false,
    expectedVerdict: "COMPLETE",
    rationale: "Normal complete Korean sentence with STOP.",
  },
  {
    id: "CI_OK_02_complete_dialogue",
    finishReason: "END_TURN",
    finalProse: "「오늘은 여기까지 하자.」 서린이 짧게 대답했다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: false,
    expectedVerdict: "COMPLETE",
    rationale: "Closed dialogue + complete narration.",
  },
  {
    id: "CI_OK_03_open_hook_complete",
    finishReason: "STOP",
    finalProse: "문이 다시 열릴지는 아무도 몰랐다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: false,
    expectedVerdict: "COMPLETE",
    rationale: "Open narrative hook but grammatically complete.",
  },
  {
    id: "CI_OK_04_unresolved_relationship",
    finishReason: "STOP",
    finalProse: "둘 사이의 거리는 좁혀지지 않았다. 서린은 그저 고개를 끄덕였다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: false,
    expectedVerdict: "COMPLETE",
    rationale: "Unresolved relationship, complete current response.",
  },
  {
    id: "CI_OK_05_silence_gaze",
    finishReason: "STOP",
    finalProse: "서린은 아무 말도 하지 않고 민의 옆얼굴을 바라봤다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: false,
    expectedVerdict: "COMPLETE",
    rationale: "Silence/gaze ending that is stylistically complete.",
  },
  {
    id: "CI_OK_06_intentional_ellipsis",
    finishReason: "STOP",
    finalProse: "그 말은 결국 입 밖으로 나오지 않았다…",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: false,
    expectedVerdict: "COMPLETE",
    rationale: "Ellipsis used intentionally as complete ending.",
  },
  {
    id: "CI_OK_07_short_complete",
    finishReason: "STOP",
    finalProse: "알았어.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: false,
    expectedVerdict: "COMPLETE",
    rationale: "Short but complete utterance.",
  },
  {
    id: "CI_OK_08_null_finish_complete",
    finishReason: null,
    finalProse: "서린은 불을 끄고 침대로 돌아갔다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: false,
    expectedVerdict: "COMPLETE",
    rationale: "finishReason null but prose complete — not a candidate.",
  },
  {
    id: "CI_OK_09_length_but_complete",
    finishReason: "MAX_TOKENS",
    finalProse: "그는 마지막 문장을 다 쓰고 펜을 내려놓았다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "COMPLETE",
    rationale: "Token-limit finishReason but final prose ends at a valid complete boundary.",
  },
  {
    id: "CI_OK_10_length_complete_dialogue",
    finishReason: "LENGTH",
    finalProse: "「내일 보자.」 그녀가 문을 닫았다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "COMPLETE",
    rationale: "LENGTH finish with complete closed dialogue.",
  },
  {
    id: "CI_OK_11_recovered_predicate",
    finishReason: "MAX_TOKENS",
    finalProse: "서린은 민의 손목을 잡은 채 조금 더 끌어당겼다.",
    localRecoveryApplied: true,
    localRecoveryActions: ["append_past_final_syllable"],
    expectDeterministicCandidate: true,
    expectedVerdict: "COMPLETE",
    rationale: "Local recovery completed the predicate; delivered prose is complete.",
  },
  {
    id: "CI_OK_12_recovered_quote",
    finishReason: "STOP",
    finalProse: "서린이 낮게 말했다. 「지금은 안 돼.」",
    localRecoveryApplied: true,
    localRecoveryActions: ["close_quote"],
    expectDeterministicCandidate: true,
    expectedVerdict: "COMPLETE",
    rationale: "Quote closed by local repair; assess delivered final prose as complete.",
  },

  // —— Uncertain ——
  {
    id: "CI_UN_01_literary_fragment",
    finishReason: "MAX_TOKENS",
    finalProse: "빗소리.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "UNCERTAIN",
    rationale: "Single-noun literary fragment with token-limit — may be intentional style or cut.",
  },
  {
    id: "CI_UN_02_terse_utterance",
    finishReason: "END_TURN",
    finalProse: "흠",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "UNCERTAIN",
    rationale: "Extremely terse utterance without clear sentence boundary.",
  },
  {
    id: "CI_UN_03_ambiguous_ellipsis",
    finishReason: "MAX_TOKENS",
    finalProse: "서린은 고개를 돌리며…",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "UNCERTAIN",
    rationale: "Ellipsis after incomplete-feeling clause with token-limit reason.",
  },
  {
    id: "CI_UN_04_quoted_fragment",
    finishReason: "LENGTH",
    finalProse: "「그거…」",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "UNCERTAIN",
    rationale: "Quoted fragment with length finish; bounded tail cannot establish intent.",
  },
  {
    id: "CI_UN_05_recovered_but_ambiguous",
    finishReason: "LENGTH",
    finalProse: "서린은 그 말을…",
    localRecoveryApplied: true,
    localRecoveryActions: ["close_quote_skipped"],
    expectDeterministicCandidate: true,
    expectedVerdict: "UNCERTAIN",
    rationale: "Recovery flagged but final ellipsis remains ambiguous.",
  },

  // —— More abrupt / complete balance ——
  {
    id: "CI_AC_10_unclosed_ascii_quote",
    finishReason: "MAX_TOKENS",
    finalProse: '민이 물었다. "왜 이제야',
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Unclosed ASCII dialogue quote.",
  },
  {
    id: "CI_OK_13_max_tokens_complete_paragraph",
    finishReason: "MAX_TOKENS",
    finalProse:
      "서린은 책상 위의 서류를 정리했다. 창밖은 이미 어두웠다. 오늘은 여기까지였다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "COMPLETE",
    rationale: "Token limit but multi-sentence complete ending.",
  },
  {
    id: "CI_OK_14_stop_complete_action",
    finishReason: "STOP",
    finalProse: "그는 커피잔을 내려놓고 출입구 쪽으로 걸음을 옮겼다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: false,
    expectedVerdict: "COMPLETE",
    rationale: "Complete action sentence; scanner-negative.",
  },
  {
    id: "CI_OK_15_length_complete_gaze",
    finishReason: "LENGTH",
    finalProse: "서린은 한참을 그렇게 서 있었다.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "COMPLETE",
    rationale: "LENGTH finishReason with a complete, self-contained gaze beat.",
  },
  {
    id: "CI_AC_11_semicolon_cut",
    finishReason: "LENGTH",
    finalProse: "계획은 단순했다; 먼저 열쇠를 찾고",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "ABRUPT_CUT",
    rationale: "Semicolon clause left unfinished.",
  },
  {
    id: "CI_UN_06_gaze_word",
    finishReason: "MAX_TOKENS",
    finalProse: "시선.",
    localRecoveryApplied: false,
    localRecoveryActions: [],
    expectDeterministicCandidate: true,
    expectedVerdict: "UNCERTAIN",
    rationale: "Single stylistic noun with token-limit; uncertain whether intentional fragment.",
  },
];
