[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
