/**
 * Phase C.1 — re-score existing Phase C JSONL artifacts with corrected analyzer.
 *
 *   node --conditions=react-server --import tsx scripts/gemini31-phase-c-rescore.ts
 */
import fs from "node:fs";
import path from "node:path";

import {
  buildPhaseC1Diagnosis,
  classifyCacheDrop,
  normalizeLegacyTurnRecord,
  type FixtureKind,
  type PhaseCTurnRecord,
} from "./lib/gemini31PhaseCAnalyzer";

const ARTIFACT_DIR = path.join(process.cwd(), "docs/audits/gemini31-phase-c-ttft");
const OUT_ARTIFACT = path.join(ARTIFACT_DIR, "report-c1.json");
const METRIC_AUDIT = path.join(ARTIFACT_DIR, "METRIC_AUDIT.md");

function loadFixture(kind: FixtureKind): PhaseCTurnRecord[] {
  const p = path.join(ARTIFACT_DIR, `turns-${kind}.jsonl`);
  const lines = fs.readFileSync(p, "utf8").trim().split("\n").filter(Boolean);
  const turns = lines.map((l) => normalizeLegacyTurnRecord(JSON.parse(l) as Record<string, unknown>));
  for (let i = 0; i < turns.length; i++) {
    turns[i]!.cache_drop_class = classifyCacheDrop(i > 0 ? turns[i - 1]! : null, turns[i]!);
  }
  return turns;
}

function writeMetricAudit(): void {
  const md = `# Phase C Metric Audit (C.1)

| Metric | Source field | Generated by | NULL semantics | ZERO semantics | Actual unit |
|--------|--------------|--------------|----------------|----------------|-------------|
| BACKGROUND_SUMMARY_OVERLAP | \`summary_contention_active\` | phase audit \`summary_contention.summaryBackgroundActiveAtProviderStart\` | N/A (boolean) | false = no overlap | enum NONE/OBSERVED |
| BACKGROUND_SUMMARY_CONTENTION | derived | \`assessSummaryContention()\` | INCONCLUSIVE if sample too small | N/A | YES/NO_EVIDENCE/INCONCLUSIVE |
| CACHE_RATIO | \`cached_tokens/prompt_tokens\` | collector/analyzer | **NOT_MEASURABLE** when \`cached_tokens\` null | 0 only when provider explicitly reports 0 | ratio 0–1 |
| CACHE_DROP_EVENTS | derived | \`classifyCacheDrop()\` | NOT_MEASURABLE when cache unavailable | NONE when no drop | enum |
| CI_SERVING_FLOOR | derived | wait/visible P50 thresholds | UNKNOWN without stage timing | N/A | CONFIRMED/NOT_CONFIRMED/UNKNOWN |
| TTFT_OWNER | derived | stage decomposition + reasoning correlation | UNKNOWN without PROVIDER_WAIT_MS | N/A | enum owner |
| COST | \`done.cost\` | route \`settlement.settledPoints\` | null if missing | 0 points possible | **user_charge_points** (not USD) |
| VISIBLE_OUTPUT_TOKENS | \`tokens.completion_tokens\` | phase audit provider stage | null if missing | provider total completion | **provider_completion_tokens** (includes reasoning) |
| PROVIDER_WAIT_MS | \`PROVIDER_WAIT_MS\` | T10→T12 phase marks | null in legacy 36-run artifacts | N/A | milliseconds |
| PROVIDER_VISIBLE_TTFT_MS | \`PROVIDER_VISIBLE_TTFT_MS\` | T10→T13 phase marks | falls back to client delta in legacy | N/A | milliseconds |
| memory_sync_to_canon_ms | \`SUMMARY_BARRIER_WAIT_MS\` | T4→T5 delta (legacy label) | null if missing | 0 possible | ms — **not summary LLM barrier post-#718** |

## Cache dataflow (read-only audit)

| Stage | RAW_FIELD_PRESENT | PARSED_VALUE | PRESENCE_PRESERVED |
|-------|-------------------|--------------|-------------------|
| CI raw SSE usage | \`prompt_tokens_details.cached_tokens\` etc. | varies by provider | unknown without inventory |
| \`parseOpenRouterUsage()\` | uses \`readNum\` / \`pickUsageField\` | **defaults missing → 0** | **NO — missing collapsed to 0** |
| \`tokenUsageFromOpenRouterBreakdown\` | cacheReadTokens | omits field when 0 | partial |
| stage \`cacheReadTokens\` | from parser | 0 when absent | NO |
| phase audit \`cached_tokens\` | set from stage | 0 or omitted | legacy collector saw null |
| Phase C legacy collector | \`tokens.cached_tokens\` | null but \`cache_ratio: 0\` bug | **NO** |
| Phase C.1 analyzer | \`cache_read_tokens_reported\` | null unless explicit | **YES** |

## COUNT_MISMATCH_ROOT_CAUSE

Legacy DIAGNOSIS stated "7/36 turns contention" aggregating **all fixtures** (A:0, B:1, C:6).
Fixture C alone: **6 active / 6 inactive** — no mismatch in raw JSONL.
`;
  fs.writeFileSync(METRIC_AUDIT, md);
}

function main() {
  const fixtures = (["A", "B", "C"] as FixtureKind[]).map((f) => ({
    fixture: f,
    turns: loadFixture(f),
  }));
  const allTurns = fixtures.flatMap((f) => f.turns);

  const diagnosis = buildPhaseC1Diagnosis(allTurns, {
    legacyReportContentionCount: 7,
    stageTimingAvailable: allTurns.some((t) => t.provider_wait_ms != null),
  });

  const report = {
    generatedAt: new Date().toISOString(),
    phase: "C.1",
    readOnly: true,
    rescoredFrom: "docs/audits/gemini31-phase-c-ttft/turns-{A,B,C}.jsonl",
    turnCount: allTurns.length,
    fixtures: Object.fromEntries(
      fixtures.map((f) => [
        f.fixture,
        {
          turnCount: f.turns.length,
          turns: f.turns,
        },
      ])
    ),
    ...diagnosis,
  };

  fs.writeFileSync(OUT_ARTIFACT, JSON.stringify(report, null, 2));
  writeMetricAudit();
  console.log(JSON.stringify(diagnosis, null, 2));
  console.log("Wrote", OUT_ARTIFACT);
  console.log("Wrote", METRIC_AUDIT);
}

main();
