/**
 * Memory baseline regression escalation.
 *
 * Converts a deterministic same-benchmark REGRESSION/MIXED trend into one
 * deduplicated GitHub investigation issue per benchmark fingerprint.
 * Research/ops only: no production mutation and no automatic fix.
 */
import type { CycleReport } from "@/lib/memoryResearch/cycle";

export type BaselineRegressionIssuePlan = {
  fingerprint: string;
  title: string;
  body: string;
};

export type ExistingIssue = {
  number: number;
  title: string;
};

function fmt(value: number | null): string {
  return value == null ? "-" : String(value);
}

export function buildBaselineRegressionIssuePlan(
  report: CycleReport
): BaselineRegressionIssuePlan | null {
  const trend = report.baselineTrend;
  if (trend.status !== "REGRESSION" && trend.status !== "MIXED") return null;
  if (!trend.benchmarkFingerprint) return null;

  const fingerprint = trend.benchmarkFingerprint;
  const title = `[memory-baseline-regression:${fingerprint}] deterministic baseline drift`;
  const regressed = trend.metricDeltas.filter((row) => row.verdict === "regressed");
  const improved = trend.metricDeltas.filter((row) => row.verdict === "improved");

  const body = [
    `<!-- memory-baseline-regression:${fingerprint} -->`,
    "# Memory baseline regression investigation",
    "",
    "This issue was generated by the existing Memory Research Cycle from deterministic local benchmark evidence. It is an investigation signal, not an automatic rollback or production patch.",
    "",
    `- cycle: \`${report.cycleKey}\``,
    `- main: \`${report.mainSha}\``,
    `- trend: **${trend.status}**`,
    `- benchmark fingerprint: \`${fingerprint}\``,
    `- previous comparable cycle: \`${trend.previousCycleKey ?? "-"}\``,
    `- prompt tokens/turn delta: ${trend.promptTokensPerTurnDelta == null ? "-" : trend.promptTokensPerTurnDelta.toFixed(2)} (${trend.promptTokenTrend})`,
    `- invariant violation delta: ${trend.invariantViolationDelta ?? "-"}`,
    "",
    "## Regressed raw metrics",
    "",
    ...(regressed.length > 0
      ? regressed.map(
          (row) =>
            `- ${row.key}: ${fmt(row.previous)} → ${fmt(row.current)} (delta ${fmt(row.delta)})`
        )
      : ["- (none)"]),
    "",
    "## Lost positive cases",
    "",
    ...(trend.lostPositiveCases.length > 0
      ? trend.lostPositiveCases.map((id) => `- \`${id}\``)
      : ["- (none)"]),
    "",
    "## Improvements observed in the same cycle",
    "",
    ...(improved.length > 0
      ? improved.map(
          (row) =>
            `- ${row.key}: ${fmt(row.previous)} → ${fmt(row.current)} (delta ${fmt(row.delta)})`
        )
      : ["- (none)"]),
    ...(trend.gainedPositiveCases.length > 0
      ? ["", ...trend.gainedPositiveCases.map((id) => `- gained case: \`${id}\``)]
      : []),
    "",
    "## Investigation contract",
    "",
    "- Reproduce the regressed raw metric/case on current main before patching.",
    "- Compare current main against the previous comparable main/cycle using the same benchmark fingerprint.",
    "- Find the canonical owner that changed; do not add a parallel memory owner.",
    "- Prompt-token growth is separate cost evidence and is not itself proof of quality regression.",
    "- If the benchmark definition changes, do not compare aggregate values across fingerprints.",
    "- Any fix requires its own reviewed PR and normal Memory CI. This issue never auto-merges or mutates production.",
    "",
  ].join("\n");

  return { fingerprint, title, body };
}

export function findOpenRegressionIssue(
  plan: BaselineRegressionIssuePlan,
  issues: readonly ExistingIssue[]
): ExistingIssue | null {
  return issues.find((issue) => issue.title === plan.title) ?? null;
}
