import type { PostTurnCallFamilySpec } from "./types";

/**
 * Static inventory of cost-bearing call families reachable from POST /api/chat.
 * Verified against main @ db448289 — re-validate on merge.
 */
export const POST_TURN_CALL_FAMILY_INVENTORY: PostTurnCallFamilySpec[] = [
  {
    id: "main_rp",
    trigger: "Normal RP stream completion",
    callSite: "src/app/api/chat/route.ts → streamOpenRouterAdultToClient",
    canonicalOwner: "streamOpenRouterAdultToClient / openRouterAdult",
    modelResolutionOwner: "route selectedAI + adult routing",
    requestKindPattern: "main-rp-*",
    syncOrAsync: "sync_await",
    inputContext: "assembled prompt + history",
    runsEveryTurn: true,
    retryOwner: "openRouterAdult fallback/handoff",
    maxLogicalAttempts: 2,
    fallbackOwner: "adult routing fallback path",
    userBilled: "main_rp_billed",
    platformFunded: false,
    usagePreserved: true,
    exactProviderCostPreserved: true,
    persistedBeforeReceipt: true,
    canRunAfterMainReceiptSnapshot: false,
    sameTurnContextDuplicatedWith: [],
    safeToCoalesceWith: [],
  },
  {
    id: "status_widget_combined_initial",
    trigger: "statusWidgetActive + creator+user both need extract",
    callSite: "src/lib/statusWidget/extract.ts → extractStatusWidgetValuesForTurn",
    canonicalOwner: "extractStatusWidgetValuesForTurn",
    modelResolutionOwner: "BACKGROUND_OPENROUTER_MODEL via StatusWidgetExtractCaller",
    requestKindPattern: "background-status-widget-extract-combined",
    syncOrAsync: "sync_await",
    inputContext: "assistantProse + userMessage + widget templates + previous values",
    runsEveryTurn: false,
    retryOwner: "extractStatusWidgetValuesForTurn repair/fallback sub-stages",
    maxLogicalAttempts: 1,
    fallbackOwner: "extractSourceWithRepairAndFallback",
    userBilled: "user_billed_aux",
    platformFunded: false,
    usagePreserved: true,
    exactProviderCostPreserved: true,
    persistedBeforeReceipt: true,
    canRunAfterMainReceiptSnapshot: false,
    sameTurnContextDuplicatedWith: ["suggested_replies_initial"],
    safeToCoalesceWith: [],
  },
  {
    id: "status_widget_initial",
    trigger: "statusWidgetActive + single source needs extract",
    callSite: "src/lib/statusWidget/extract.ts",
    canonicalOwner: "extractStatusWidgetValuesForTurn",
    modelResolutionOwner: "BACKGROUND_OPENROUTER_MODEL",
    requestKindPattern: "background-status-widget-extract",
    syncOrAsync: "sync_await",
    inputContext: "assistantProse + userMessage + one widget template",
    runsEveryTurn: false,
    retryOwner: "extractSourceWithRepairAndFallback",
    maxLogicalAttempts: 1,
    fallbackOwner: "extractSourceWithRepairAndFallback",
    userBilled: "user_billed_aux",
    platformFunded: false,
    usagePreserved: true,
    exactProviderCostPreserved: true,
    persistedBeforeReceipt: true,
    canRunAfterMainReceiptSnapshot: false,
    sameTurnContextDuplicatedWith: ["suggested_replies_initial"],
    safeToCoalesceWith: [],
  },
  {
    id: "status_widget_repair",
    trigger: "parse/validation failure after initial",
    callSite: "src/lib/statusWidget/extract.ts",
    canonicalOwner: "extractSourceWithRepairAndFallback",
    modelResolutionOwner: "primary/fallback model ids per stage",
    requestKindPattern: "background-status-widget-extract-repair|volatile-echo-fix",
    syncOrAsync: "sync_await",
    inputContext: "same turn + malformed JSON context",
    runsEveryTurn: false,
    retryOwner: "per-source repair loop",
    maxLogicalAttempts: 2,
    fallbackOwner: "extractSourceWithRepairAndFallback",
    userBilled: "user_billed_aux",
    platformFunded: false,
    usagePreserved: true,
    exactProviderCostPreserved: true,
    persistedBeforeReceipt: true,
    canRunAfterMainReceiptSnapshot: false,
    sameTurnContextDuplicatedWith: [],
    safeToCoalesceWith: [],
  },
  {
    id: "suggested_replies_initial",
    trigger: "suggestedRepliesEnabled after stream save",
    callSite: "src/lib/suggestedReplies/job.ts → extractSuggestedRepliesFromTurn",
    canonicalOwner: "scheduleSuggestedRepliesExtraction / runSuggestedRepliesExtraction",
    modelResolutionOwner: "callBackgroundMemory default BACKGROUND_OPENROUTER_MODEL",
    requestKindPattern: "background-suggested-replies-extract",
    syncOrAsync: "async_fire_forget",
    inputContext: "assistantProse (6000 char cap) + userMessage + persona",
    runsEveryTurn: false,
    retryOwner: "runSuggestedRepliesExtraction (max 3)",
    maxLogicalAttempts: 3,
    fallbackOwner: "none",
    userBilled: "platform_funded",
    platformFunded: true,
    usagePreserved: false,
    exactProviderCostPreserved: false,
    persistedBeforeReceipt: true,
    canRunAfterMainReceiptSnapshot: true,
    sameTurnContextDuplicatedWith: ["status_widget_combined_initial", "status_widget_initial"],
    safeToCoalesceWith: [],
  },
  {
    id: "status_meta_initial",
    trigger: "statusMetaEnabled after stream save",
    callSite: "src/lib/statusMeta/job.ts → extractStatusMetaFromTurn",
    canonicalOwner: "scheduleStatusMetaExtraction",
    modelResolutionOwner: "callBackgroundMemory",
    requestKindPattern: "background-status-meta-extract",
    syncOrAsync: "async_fire_forget",
    inputContext: "assistantProse + previousMeta + memory + lore + userNote + formatSpec",
    runsEveryTurn: false,
    retryOwner: "runStatusMetaExtraction (max 3)",
    maxLogicalAttempts: 3,
    fallbackOwner: "none",
    userBilled: "platform_funded",
    platformFunded: true,
    usagePreserved: false,
    exactProviderCostPreserved: false,
    persistedBeforeReceipt: true,
    canRunAfterMainReceiptSnapshot: true,
    sameTurnContextDuplicatedWith: [],
    safeToCoalesceWith: [],
  },
  {
    id: "memory_update",
    trigger: "scheduleMemoryUpdate after stream finalize IIFE",
    callSite: "src/lib/memory/memory-manager.ts",
    canonicalOwner: "scheduleMemoryUpdate",
    modelResolutionOwner: "callBackgroundMemory",
    requestKindPattern: "background-memory-extract",
    syncOrAsync: "async_fire_forget",
    inputContext: "user+assistant turn pair + relationship context",
    runsEveryTurn: false,
    retryOwner: "memory batch processors",
    maxLogicalAttempts: 1,
    fallbackOwner: "rolling summary path",
    userBilled: "none",
    platformFunded: true,
    usagePreserved: false,
    exactProviderCostPreserved: false,
    persistedBeforeReceipt: true,
    canRunAfterMainReceiptSnapshot: true,
    sameTurnContextDuplicatedWith: [],
    safeToCoalesceWith: [],
  },
];

export function listPostTurnCostBearingFamilies(): PostTurnCallFamilySpec[] {
  return POST_TURN_CALL_FAMILY_INVENTORY;
}

export function familiesRunningAfterReceiptSnapshot(): PostTurnCallFamilySpec[] {
  return POST_TURN_CALL_FAMILY_INVENTORY.filter((f) => f.canRunAfterMainReceiptSnapshot);
}
